pipeline {
    agent any
    environment {
        MAVEN_HOME = "/opt/apache-maven-3.9.8"
        PATH = "PATH=$PATH:$MAVEN_HOME/bin"
    }
    stages {
        stage("Clean Up"){
            steps {
                deleteDir()
            }
        }
        stage("Clone Repo"){
            steps {
                sh "git clone https://github.com/jenkins-docs/simple-java-maven-app.git"
            }
        }
        stage("Build"){
            steps {
                dir("simple-java-maven-app"){
                    sh "mvn clean install"
                }
            }
        }
        stage("Test"){
            steps {
                dir("simple-java-maven-app"){
                    sh "mvn test"
                }
            }
        }
    }
}

